create table "account"
(
	acc_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	username text unique,
	firstname text,
	lastname text,
	password text,
	mobile_num text,
	admin_prev boolean
);

-- insert into account(username,firstname,lastname,password,mobile_num,admin_prev) values
-- ('joren35','Joren Mundane','Pacaldo', 'celeron0912', '09675974534', False)
--
-- select * from account

create or replace function user_credentials(out text, out text, out text, out text, out BOOLEAN) returns setof record as
$$
   select username,firstname,lastname,mobile_num,admin_prev from "account";
$$
 language 'sql';

create or replace function register(in par_username text, in par_firstname text, in par_lastname text, in par_password text,
                                    in par_mobile text,in par_admin_prev boolean) returns text as
$$
  declare
    loc_res text;
	loc_username text;

  begin
  	select into loc_username username from account where username = par_username;
	if loc_username isnull then
     insert into account(username,firstname,lastname,password,mobile_num,admin_prev) values
      (par_username,par_firstname,par_lastname, par_password, par_mobile, par_admin_prev);
      loc_res = 'ok';
	else
	 loc_res = 'Error Username Exist';
	 end if;
     return loc_res;
  end;
$$
LANGUAGE plpgsql;